blank_issues_enabled: false
contact_links:

  - name: FOR EXPLOITS ONLY!!
    url: https://docs.google.com/forms/d/e/1FAIpQLScFSPhrlPpo0K1zRsRkokJVWK7RZVtEbyN7k3ZupLf8yheCbg/viewform
    about: This is a form where you can report gamebreaking bugs or exploits that gives unfair advantages for players. No "normal" reports are allowed here, as they will be ignored!
  - name: IMPORTANT Read before making a bug report!!
    url: https://github.com/WoWManiaUK/Redemption/blob/master/CONTRIBUTING.md
    about: This contains info on how to properly report a bug.
  - name: WoW-Mania Community Forum
    url: https://wow-mania.com/forum/
    about: Please ask and answer questions here.
  - name: WoW-Mania Suggestions
    url: https://wow-mania.com/forum/viewforum.php?f=11&sid=7693b7cdd7439836ee2ac7d721de4a25
    about: Please make any suggestions you may have here.
  - name: Connection issues
    url: https://wow-mania.com/forum/viewtopic.php?f=13&t=9
    about: Please read this guide for connection issues.
